apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jN2l1NmV3NmlpNmIudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: bW9oYW1tYWRyYWZlZXE=
